version: '3.9'

services:

  mysql:
    image: mysql:8.0
    container_name: mysql_cache_demo
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: biller_db

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7
    container_name: redis_cache_demo
    restart: always

    ports:
      - "6379:6379"

    command: redis-server --appendonly yes

    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data: